pipeline {
    agent any
    parameters {
        booleanParam(defaultValue:false, description: "Enable service?", name: "myBool")
    }

    stages {
        stage {
            steps("demo"){
                echo "booleanParam is set to : ${myBool}"
        }
    }
}