pipeline {
    agent any
    parameters {
        booleanParam(defaultValue:false, description: "Enable service?", name: "myBool")
    }

    stages {
        stage ("demo"){
            steps{
                echo "booleanParam is set to : ${myBool}"
            }
        }
    }
}