pipeline {
    agent any
    stages {
        stage("stage 1") {
            steps {
                echo "This is stage 1next stage 2, challenge 2 edited"
            }
        }
        stage("stage 2") {
            steps {
                echo "This is stage 2"
            }
        }
        stage("stage 3") {
            steps {
                echo "This is stage 3"
            }
        }
        stage("stage 4") {
            steps {
                echo "This is stage 4"
            }
        }
        stage("stage 5") {
            steps {
                echo "Stage 6 deleted for hooks trigger check along with jenkins token updated properly"
            }
        }
    }
}
