pipeline {
    agent any
    environment {
        def greet = "World!"
    }
    stages {
        stage ("demo"){
            steps{
                echo "Welcome ${greet}"
                echo "Current build number : ${env.BUILD_NUMBER}"
            }
        }
    }
}