pipeline {
    agent any
    parameters {
        choice(choices:["Test", "Dev", "QA", "Prod"], description: "Enable service?", name: "myChoice")
    }
    stages {
        stage ("demo"){
            steps{
                echo "Hello World!"
                echo "Build is ready for \"${myChoice}\" Environment"
            }
        }
    }
}